services:
  lockbox:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - DATABASE_PATH=/app/data/lockbox.db
      - FLASK_ENV=production
    restart: unless-stopped